[package]
name = "minigrep_4_study_rust"
version = "0.1.0"
edition = "2021"
description = "practice demo for study rust"
authors = ["secretx500 <secretx500@qq.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
